name: Build and publish

on:
  push:
    tags:
    - "*"

jobs:

  build-and-publish-tag:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and publish Docker image tagged according to a git-tag
      uses: VaultVulp/gp-docker-action@1.6.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: external-secrets-bitwarden
        extract-git-tag: true
